package hyprland

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	BindingsFileName       = "kiekje-bindings.conf"
	LegacyBindingsFileName = "cheese-bindings.conf"
	ManagedByComment       = "# Managed by Kiekje."
	SourceComment          = "# Kiekje capture shortcuts"
)

var managedSourceRe = regexp.MustCompile(`(?i)^\s*source\s*=.*\b(kiekje-bindings|cheese-bindings)\.conf\b`)

// ConfigDir returns ~/.config/hypr.
func ConfigDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "hypr"), nil
}

// BindingsPath returns the managed snippet path.
func BindingsPath() (string, error) {
	dir, err := ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, BindingsFileName), nil
}

// MainConfigPath returns ~/.config/hypr/hyprland.conf.
func MainConfigPath() (string, error) {
	dir, err := ConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "hyprland.conf"), nil
}

// SourceLine is the relative source directive Hyprland expects beside hyprland.conf.
func SourceLine() string {
	return "source = ./" + BindingsFileName
}

// WindowRules returns the floating-window rules for the capture editor.
func WindowRules() string {
	return strings.TrimSpace(`
windowrule = float on, match:title ^(Kiekje)$
windowrule = no_initial_focus on, match:title ^(Kiekje)$
windowrule = workspace current silent, match:title ^(Kiekje)$
windowrule = center on, match:title ^(Kiekje)$
`)
}

// BuildBindingsContent renders the managed snippet body.
func BuildBindingsContent(bindLines string) string {
	bindLines = strings.TrimSpace(bindLines)
	if bindLines == "" {
		return ManagedByComment + "\n" + WindowRules() + "\n"
	}
	return ManagedByComment + "\n" + WindowRules() + "\n" + bindLines + "\n"
}

// EnsureSourceLine inserts or upgrades the managed source directive in hyprland.conf content.
func EnsureSourceLine(content string) (string, bool) {
	lines := strings.Split(content, "\n")
	filtered := make([]string, 0, len(lines)+2)
	hasKiekje := false
	changed := false

	for _, line := range lines {
		if !managedSourceRe.MatchString(line) {
			filtered = append(filtered, line)
			continue
		}
		if strings.Contains(strings.ToLower(line), BindingsFileName) {
			hasKiekje = true
			filtered = append(filtered, line)
			continue
		}
		changed = true
	}

	if hasKiekje {
		return strings.TrimRight(strings.Join(filtered, "\n"), "\n") + "\n", changed
	}

	if len(filtered) > 0 && strings.TrimSpace(filtered[len(filtered)-1]) != "" {
		filtered = append(filtered, "")
	}
	filtered = append(filtered, SourceLine()+" "+SourceComment)
	return strings.TrimRight(strings.Join(filtered, "\n"), "\n") + "\n", true
}

// Sync writes the managed snippet and ensures hyprland.conf sources it.
func Sync(bindLines string) error {
	hyprDir, err := ConfigDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(hyprDir, 0o755); err != nil {
		return err
	}

	bindsPath, err := BindingsPath()
	if err != nil {
		return err
	}
	if err := os.WriteFile(bindsPath, []byte(BuildBindingsContent(bindLines)), 0o644); err != nil {
		return err
	}

	mainPath, err := MainConfigPath()
	if err != nil {
		return err
	}

	raw, err := os.ReadFile(mainPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		raw = []byte("# Generated by Kiekje.\n")
	}

	updated, _ := EnsureSourceLine(string(raw))
	if err := os.WriteFile(mainPath, []byte(updated), 0o644); err != nil {
		return err
	}

	_ = Reload()
	return nil
}

// Reload asks Hyprland to reload config when a session is active.
func Reload() error {
	if _, err := exec.LookPath("hyprctl"); err != nil {
		return nil
	}
	if os.Getenv("HYPRLAND_INSTANCE_SIGNATURE") == "" {
		return nil
	}
	if err := exec.Command("hyprctl", "reload").Run(); err != nil {
		return fmt.Errorf("hyprctl reload: %w", err)
	}
	return nil
}
