// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCapture() {
  return window['go']['main']['App']['CancelCapture']();
}

export function CaptureRegionAt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CaptureRegionAt'](arg1, arg2, arg3, arg4);
}

export function ChooseSaveDir() {
  return window['go']['main']['App']['ChooseSaveDir']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function GetWindowGeometryAtPoint(arg1, arg2) {
  return window['go']['main']['App']['GetWindowGeometryAtPoint'](arg1, arg2);
}

export function GetWindowGeometryAtCursor() {
  return window['go']['main']['App']['GetWindowGeometryAtCursor']();
}

export function FinishCapture() {
  return window['go']['main']['App']['FinishCapture']();
}

export function GetHyprlandSnapshot() {
  return window['go']['main']['App']['GetHyprlandSnapshot']();
}

export function HandleSecondInstance(arg1) {
  return window['go']['main']['App']['HandleSecondInstance'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallAutostart() {
  return window['go']['main']['App']['InstallAutostart']();
}

export function InstallGlobalShortcuts() {
  return window['go']['main']['App']['InstallGlobalShortcuts']();
}

export function LoadAppState() {
  return window['go']['main']['App']['LoadAppState']();
}

export function OpenLastImage() {
  return window['go']['main']['App']['OpenLastImage']();
}

export function OpenSaveDir() {
  return window['go']['main']['App']['OpenSaveDir']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RequestCapture() {
  return window['go']['main']['App']['RequestCapture']();
}

export function ResetBinds() {
  return window['go']['main']['App']['ResetBinds']();
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function ShowCaptureSuccessToast() {
  return window['go']['main']['App']['ShowCaptureSuccessToast']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateBind(arg1, arg2) {
  return window['go']['main']['App']['UpdateBind'](arg1, arg2);
}

export function UpdateSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2, arg3, arg4, arg5);
}
