// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelCapture():Promise<void>;

export function CaptureRegionAt(arg1:number,arg2:number,arg3:number,arg4:number):Promise<main.CaptureResult>;

export function ChooseSaveDir():Promise<main.AppState>;

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function GetWindowGeometryAtPoint(arg1:number,arg2:number):Promise<main.WindowGeometry>;

export function GetWindowGeometryAtCursor():Promise<main.WindowGeometry>;

export function FinishCapture():Promise<void>;

export function GetHyprlandSnapshot():Promise<main.HyprlandSnapshot>;

export function HandleSecondInstance(arg1:Array<string>):Promise<void>;

export function HideWindow():Promise<void>;

export function InstallAutostart():Promise<void>;

export function InstallGlobalShortcuts():Promise<void>;

export function LoadAppState():Promise<main.AppState>;

export function OpenLastImage():Promise<void>;

export function OpenSaveDir():Promise<void>;

export function QuitApp():Promise<void>;

export function RequestCapture():Promise<void>;

export function ResetBinds():Promise<main.AppState>;

export function SaveImage(arg1:string,arg2:string):Promise<void>;

export function ShowCaptureSuccessToast():Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateBind(arg1:string,arg2:string):Promise<main.AppState>;

export function UpdateSettings(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<main.AppState>;
