// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureRegion() {
  return window['go']['main']['App']['CaptureRegion']();
}

export function GetHyprlandSnapshot() {
  return window['go']['main']['App']['GetHyprlandSnapshot']();
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}
