use crate::settings::config::{CaptureMode, Settings};
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

const AUTOSTART_FILE: &str = "screeny-tray.desktop";
const HYPRLAND_SHORTCUTS_FILE: &str = "screeny-shortcuts.conf";

pub fn tray_autostart_path() -> Result<PathBuf> {
    Ok(xdg_config_dir()?.join("autostart").join(AUTOSTART_FILE))
}

pub fn tray_autostart_enabled() -> Result<bool> {
    Ok(tray_autostart_path()?.exists())
}

pub fn write_tray_autostart_entry(exe: &Path) -> Result<PathBuf> {
    let path = tray_autostart_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!("failed to create autostart directory {}", parent.display())
        })?;
    }
    fs::write(&path, tray_autostart_desktop_entry(exe))
        .with_context(|| format!("failed to write tray autostart entry to {}", path.display()))?;
    Ok(path)
}

pub fn remove_tray_autostart_entry() -> Result<()> {
    let path = tray_autostart_path()?;
    if path.exists() {
        fs::remove_file(&path)
            .with_context(|| format!("failed to remove autostart entry {}", path.display()))?;
    }
    Ok(())
}

pub fn hyprland_include_path() -> Result<PathBuf> {
    Ok(xdg_config_dir()?.join("hypr").join(HYPRLAND_SHORTCUTS_FILE))
}

pub fn hyprland_bindings(settings: &Settings, exe: &Path) -> String {
    let exe = shell_quote(&exe.display().to_string());
    let mut out = String::new();
    out.push_str("# Screeny keyboard shortcuts\n");
    out.push_str("# Generated by capture-app --launcher\n");

    for (mode, shortcut) in [
        (CaptureMode::Region, settings.shortcut_region.as_str()),
        (
            CaptureMode::Fullscreen,
            settings.shortcut_fullscreen.as_str(),
        ),
        (CaptureMode::Window, settings.shortcut_window.as_str()),
    ] {
        let shortcut = shortcut.trim();
        if shortcut.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "bind = {}, exec, {} {}\n",
            shortcut,
            exe,
            capture_mode_label(mode)
        ));
    }

    out
}

pub fn write_hyprland_bindings(settings: &Settings, exe: &Path) -> Result<PathBuf> {
    let path = hyprland_include_path()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| {
            format!(
                "failed to create Hyprland config directory {}",
                parent.display()
            )
        })?;
    }
    fs::write(&path, hyprland_bindings(settings, exe)).with_context(|| {
        format!(
            "failed to write Hyprland shortcut include to {}",
            path.display()
        )
    })?;
    Ok(path)
}

pub fn hyprland_source_line() -> Result<String> {
    Ok(format!("source = {}", hyprland_include_path()?.display()))
}

fn tray_autostart_desktop_entry(exe: &Path) -> String {
    format!(
        "[Desktop Entry]\nType=Application\nVersion=1.0\nName=Screeny Tray\nComment=Start the Screeny tray icon on login\nExec={} --tray\nTerminal=false\nCategories=Utility;Graphics;\nX-GNOME-Autostart-enabled=true\n",
        exe.display()
    )
}

fn xdg_config_dir() -> Result<PathBuf> {
    if let Some(xdg) = std::env::var_os("XDG_CONFIG_HOME") {
        return Ok(PathBuf::from(xdg));
    }

    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME and XDG_CONFIG_HOME are not set")?;
    Ok(home.join(".config"))
}

fn shell_quote(value: &str) -> String {
    let escaped = value.replace('\'', r#"'\''"#);
    format!("'{}'", escaped)
}

fn capture_mode_label(mode: CaptureMode) -> &'static str {
    match mode {
        CaptureMode::Region => "region",
        CaptureMode::Fullscreen => "fullscreen",
        CaptureMode::Window => "window",
    }
}

#[cfg(test)]
mod tests {
    use super::{hyprland_bindings, hyprland_source_line, tray_autostart_desktop_entry};
    use crate::settings::config::Settings;
    use std::path::Path;

    #[test]
    fn renders_tray_desktop_entry() {
        let entry = tray_autostart_desktop_entry(Path::new("/tmp/capture-app"));
        assert!(entry.contains("Exec=/tmp/capture-app --tray"));
        assert!(entry.contains("Name=Screeny Tray"));
    }

    #[test]
    fn renders_hyprland_binding_lines() {
        let settings = Settings::default();
        let body = hyprland_bindings(&settings, Path::new("/tmp/capture-app"));

        assert!(body.contains("bind = SUPER SHIFT, S, exec, '/tmp/capture-app' region"));
        assert!(body.contains("bind = SUPER SHIFT, F, exec, '/tmp/capture-app' fullscreen"));
        assert!(body.contains("bind = SUPER SHIFT, W, exec, '/tmp/capture-app' window"));
    }

    #[test]
    fn source_line_mentions_generated_include() {
        let line = hyprland_source_line().unwrap();
        assert!(line.contains("screeny-shortcuts.conf"));
    }
}
